name: CI Multiplatform Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ feature-github-ci ]

jobs:
  macosBuild:
   runs-on: macos-latest

   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Install deps
       run: ./ci/macos/install-dependencies-macos.sh
     - name: Install obs
       run: ./ci/macos/install-build-obs-macos.sh
     - name: Compile
       run: ./ci/macos/build-macos.sh

  ubuntuBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: | 
          sudo apt-get update && sudo apt-get install -y \
            g++-multilib \
            gcc-multilib \
            git \
            wget \
      - name: OBS deps
        run: ./ci/linux/install-dependencies-ubuntu.sh
      - name: Compile
        run: ./ci/linux/build-ubuntu.sh

  windowsBuild:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        shell: cmd
        run: .\ci\windows\download-obs-deps.cmd
      - name: OBS deps
        shell: cmd
        run: .\ci\windows\prepare-obs-windows.cmd
      - name: Compile
        shell: cmd
        run: .\ci\windows\prepare-windows.cmd
