name: CI Multiplatform Build

on:
  push:
    branches: [feature-github-ci]
  pull_request:
    branches: [ main ]

jobs:  
  ubuntuBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: | 
          sudo apt-get update && sudo apt-get install -y \
            g++-multilib \
            gcc-multilib \
            git \
            wget \
      - name: OBS deps
        run: ./plugin/ci/linux/install-dependencies-ubuntu.sh
      - name: Compile
        run: ./plugin/ci/linux/build-ubuntu.sh
  
  macos64Build:
    name: 'macOS 64-bit'
    runs-on: [macos-latest]
    steps:
      - name: Get Current Arch
        shell: bash
        id: get_arch
        run: echo "CURRENT_ARCH=$(uname -m)" >> $GITHUB_ENV
      - name: 'Checkout'
        uses: actions/checkout@v2.3.3
        with:
          submodules: 'recursive'
      - name: Install deps
        run: ./install-dependencies-macos.sh
      -name: Compile
        run: ./build-macos.sh
