name: CI Multiplatform Build

on:
  push:
    branches: [feature-github-ci]
  pull_request:
    branches: [ main ]

jobs:
  macosBuild:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install deps
        run: ./plugin/ci/macos/install-dependencies-macos.sh
      - name: Compile
        run: ./plugin/ci/macos/build-macos.sh

  ubuntuBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: | 
          sudo apt-get update && sudo apt-get install -y \
            g++-multilib \
            gcc-multilib \
            git \
            wget \
      - name: OBS deps
        run: ./ci/linux/install-dependencies-ubuntu.sh
      - name: Compile
        run: ./plugin/ci/linux/build-ubuntu.sh
